# Generated by Django 3.2.4 on 2021-06-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='value',
            field=models.CharField(default='', max_length=255),
        ),
    ]
