# Generated by Django 3.2.4 on 2021-06-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
