# Generated by Django 3.2.4 on 2021-06-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_menuitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='value',
            new_name='price',
        ),
    ]
